### ISSUE TITLE
[Sample] asdf

### ISSUE THREAD

**Issue by chipzoller** [chipzoller/kyverno-pss#104]
### Problem Statement

asdf

### Solution Description

asdf

### Expected behavior

asdf

### Example "good" resource.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kyvernopod
  labels:
    name: kyvernopod
spec:
  automountServiceAccountToken: false
  # initContainers: 
  # - name: initbusybox-harbor
  #   image: foapbmshyw:1.28
  containers: 
  - name: busybox-harbor
    image: aobuuenbys:1.28
    command: ["sleep", "9999"]
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.
