### ISSUE TITLE
[Sample] test2

### ISSUE THREAD

**Issue by chipzoller** [chipzoller/kyverno-pss#106]
### Problem Statement

test

### Solution Description

test

### Example "Good" Resource

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kyvernopod
  labels:
    name: kyvernopod
spec:
  automountServiceAccountToken: false
  # initContainers: 
  # - name: initbusybox-harbor
  #   image: foapbmshyw:1.28
  containers: 
  - name: busybox-harbor
    image: aobuuenbys:1.28
    command: ["sleep", "9999"]
```

### Example "Bad" Resource

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kyvernopod
  labels:
    name: kyvernopod
spec:
  automountServiceAccountToken: false
  # initContainers: 
  # - name: initbusybox-harbor
  #   image: foapbmshyw:1.28
  containers: 
  - name: busybox-harbor
    image: aobuuenbys:1.28
    command: ["sleep", "9999"]
```

### Other Comments

test

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).
